---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: springcloud/pipeline-base

inputs:
  - name: repo

outputs:
  - name: out

caches:
  - path: maven

run:
  path: /bin/bash
  args:
    - repo/ci/concourse/tasks/build-and-upload/task.sh