---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: maven:3.5-jdk-8-alpine
inputs:
  - pipeline-demo
outputs:
  - name: out
caches:
  - path: maven
run:
  path: /bin/bash
  args:
    - tools/concourse/tasks/build-and-upload/task.sh