resources:
- name: repo
  type: git
  source:
    uri: ((repo-url))
    branch: master
    private_key: ((private-key))

- name: version
  type: git
  source:
    uri: ((repo-url))
    branch: version
    private_key: ((private-key))

- name: deploy-app
  type: cf
  source:
    api: ((cf-api-url))
    username: ((cf-username))
    password: ((cf-password))
    organization: ((cf-org))
    space: ((cf-space))

jobs:
- name: generate-version
  public: true
  plan:
  - aggregate:
    - get: repo
    - get: version
  - task: generate-version
    file: repo/ci/concourse/tasks/generate-version/task.yml
    params:
      GIT_EMAIL: ((git-email))
      GIT_NAME: ((git-name))
  - put: version
    params:
      repository: updated-version

- name: build-and-upload
  serial: true
  public: false
  plan:
  - aggregate:
    - get: repo
    - get: version
      resource: version
      passed:
      - generate-version
      trigger: true
  - task: build-and-upload
    file: repo/ci/concourse/tasks/build-and-upload/task.yml
    params:
      <<: *common-params
  - put: repo
    params:
      repository: out
      tag: out/tag
      only_tag: true

- name: test-deploy
  serial: true
  public: false
  plan:
  - aggregate:
    - get: repo
    - get: version
      resource: version
      passed:
      - build-and-upload
      trigger: true
  - put: deploy-app
    params:
      manifest: repo/manifest.yml

common-params: &common-params
  _JAVA_OPTIONS: -Djava.security.edg=file:/dev/./urandom
  GIT_EMAIL: ((git-email))
  GIT_NAME: ((git-name))